# TODO: placeholder

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    env_file:
      - .env
    networks:
      - golps

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   restart: always
  #   env_file:
  #     - .env
  #   networks:
  #     - golps

networks:
  golps:
    name: golps
    ipam:
      driver: default