app:
  name: go-learn-pattern-state
  version: "1.0.0"
  environment: dev # dev | stage | prod

logger:
  mode: dev # debug | dev | stage | prod
  kibana_host: "0.0.0.0"
  kibana_port: "5601"
  kibana_index: go-learn-pattern-state

redis:

telegram:
